name: KFP Component YAML Test

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - 'components/**/*.yaml'
      - 'test/presubmit-component-yaml.sh'
      - 'sdk/python/**'
      - 'api/v2alpha1/**'
      - '.github/workflows/component-yaml.yml'

  workflow_dispatch:

jobs:
  test-component-yaml-kfp:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run component YAML tests
        run: ./test/presubmit-component-yaml.sh
