name: E2E Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /home/runner/.kube/config
      KIND_CLUSTER_NAME: kfp

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Create k8s Kind Cluster
      uses: container-tools/kind-action@v2
      with:
        cluster_name: ${{ env.KIND_CLUSTER_NAME }}
        kubectl_version: v1.29.2
        version: v0.22.0
        node_image: kindest/node:v1.29.2

    - name: Run E2E Tests
      run: |
        echo "Running E2E Tests"
        ./test/presubmit-tests-with-pipeline-deployment.sh --workflow_file e2e_test_kind_v2.yaml --test_result_folder e2e_test
    - name: Tear down Kind cluster
      run: kind delete cluster --name ${{ env.KIND_CLUSTER_NAME }}
