name: KFP SDK Tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/kfp-sdk-tests.yml'
      - 'sdk/**'
      - 'test/presubmit-tests-sdk.sh'

  workflow_dispatch:

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r ./test/sdk-execution-tests/requirements.txt

      - name: Run SDK Tests
        run: |
          chmod +x ./test/presubmit-tests-sdk.sh
          ./test/presubmit-tests-sdk.sh
