name: KFP Runtime Code Tests

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - '.github/workflows/kfp-runtime-tests.yml'
      - 'sdk/python/**'
      - 'test/presubmit-test-kfp-runtime-code.sh'
  workflow_dispatch:

jobs:
  kfp-runtime-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Run KFP Runtime Code Tests
        run: |
          export PULL_NUMBER="10989"
          chmod +x ./test/presubmit-test-kfp-runtime-code.sh
          ./test/presubmit-test-kfp-runtime-code.sh
