name: KFP SDK Docformatter Test

on:
  push:
    branches: [master]

  pull_request:
    paths:
      - 'sdk/python/**'
      - 'test/presubmit-docformatter-sdk.sh'
      - '.github/workflows/sdk-docformatter.yml'

  workflow_dispatch:

jobs:
  test-docformatter-kfp-sdk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: apt-get update
        run: sudo apt-get update

      - name: Install protobuf-compiler
        run: sudo apt-get install protobuf-compiler -y

      - name: Install setuptools
        run: | 
          pip3 install setuptools
          pip3 freeze

      - name: Install Wheel
        run: pip3 install wheel==0.42.0

      - name: Install protobuf
        run: pip3 install protobuf==4.25.3

      - name: Generate API proto files
        working-directory: ./api
        run: make clean python

      - name: Install kfp-pipeline-spec from source
        run: |
          python3 -m pip install api/v2alpha1/python

      - name: Install requirements
        run: pip install -r ./test/sdk-execution-tests/requirements.txt

      - name: Run docformatter tests
        run: ./test/presubmit-docformatter-sdk.sh
